#!/usr/bin/env python3
"""Convert the three original GIFs to bounded, lossless animation atlases.

Usage: python3 tools/build-traffic-sheets.py /path/to/original-gifs
Only this optional art build uses Pillow; gameplay and CI have no dependency.
Original image proportions, transparent padding, every frame and duration are
represented in metadata; no original art or remote fallback is replaced.
"""
import hashlib
import json
import math
from pathlib import Path
import sys
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'assets' / 'traffic'
SOURCES = [
    'https://i.postimg.cc/xj3VcRP3/Ship1.gif',
    'https://i.postimg.cc/T1LNxnfz/Ship2.gif',
    'https://i.postimg.cc/1zM9TVmz/Ship3.gif',
]


def build(source_dir):
    OUT.mkdir(parents=True, exist_ok=True)
    records = []
    for index, url in enumerate(SOURCES, 1):
        source = source_dir / f'Ship{index}.gif'
        with Image.open(source) as gif:
            durations, bounds = [], []
            for frame in range(gif.n_frames):
                gif.seek(frame)
                bounds.append(gif.convert('RGBA').getbbox())
                durations.append(gif.info.get('duration', 40))
            visible = [box for box in bounds if box]
            crop = (min(b[0] for b in visible), min(b[1] for b in visible),
                    max(b[2] for b in visible), max(b[3] for b in visible))
            width, height = crop[2] - crop[0], crop[3] - crop[1]
            scale = min(1, 320 / max(width, height))
            frame_w, frame_h = math.ceil(width * scale - 1e-9), math.ceil(height * scale - 1e-9)
            columns, count = 8, gif.n_frames
            atlas = Image.new('RGBA', (frame_w * columns, frame_h * math.ceil(count / columns)))
            for frame in range(count):
                gif.seek(frame)
                image = gif.convert('RGBA').crop(crop).resize((frame_w, frame_h), Image.Resampling.NEAREST)
                atlas.paste(image, (frame % columns * frame_w, frame // columns * frame_h))
            path = OUT / f'ship-{index}.webp'
            atlas.save(path, 'WEBP', lossless=True, method=6)
            record = {'image': f'assets/traffic/{path.name}', 'sourceUrl': url,
                      'sourceSHA256': hashlib.sha256(source.read_bytes()).hexdigest(),
                      'sourceWidth': gif.width, 'sourceHeight': gif.height,
                      'trim': {'x': crop[0], 'y': crop[1], 'width': width, 'height': height},
                      'frameWidth': frame_w, 'frameHeight': frame_h, 'columns': columns,
                      'frameCount': count, 'durationsMs': durations, 'durationMs': sum(durations),
                      'atlasWidth': atlas.width, 'atlasHeight': atlas.height,
                      'atlasSHA256': hashlib.sha256(path.read_bytes()).hexdigest()}
            records.append(record)
            print(path.name, path.stat().st_size, 'bytes;', atlas.width * atlas.height * 4, 'decoded bytes')
    data = json.dumps(records, indent=2)
    (OUT / 'manifest.json').write_text(data + '\n')
    (ROOT / 'src/engine/traffic-sheets.js').write_text(
        '// Generated by tools/build-traffic-sheets.py from the original GIF exports.\n'
        'window.FILE_MANIFEST = window.FILE_MANIFEST || [];\n'
        'window.FILE_MANIFEST.push({ name: "src/engine/traffic-sheets.js", exports: ["BARCODE.trafficSheets"], dependencies: [] });\n'
        'window.BARCODE = window.BARCODE || {};\nwindow.BARCODE.trafficSheets = ' + data + ';\n')


if __name__ == '__main__':
    build(Path(sys.argv[1]))
